name: rollapi
description: Dart library for Roll-API
version: 1.2.1
repository: https://github.com/TheLastGimbus/rollapi_dart
homepage: https://the.lastgimbus.com/rollplay/
issue_tracker: https://github.com/TheLastGimbus/rollapi_dart/issues

executables:
  rollapi: rollapi

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: '>=0.12.0 <1.0.0'
  args: '>=2.0.0 <3.0.0'
  logger: '>=1.0.0 <2.0.0'
  any_base: '>=2.0.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.2
