name: rollapi
description: Dart library for Roll-API
version: 0.0.1
homepage: https://github.com/TheLastGimbus/rollapi_dart

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  http: ^0.13.1

dev_dependencies:
  pedantic: ^1.9.0
